name: Auto Generate README

on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # allow committing changes

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Generate README
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cat > generate_readme.py << 'EOF'
          import os
          from openai import OpenAI

          client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

          response = client.chat.completions.create(
              model="gpt-4o-mini",
              messages=[
                  {"role": "user", "content": "Write a detailed README.md for this project with installation, usage, and contribution sections."}
              ],
              max_tokens=500,
          )

          with open("README.md", "w", encoding="utf-8") as f:
              f.write(response.choices[0].message.content)
          EOF

          python generate_readme.py

      - name: Commit README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-generated README via OpenAI" || echo "No changes to commit"
          git push
